version: "3.3"
# docker for linux and raspberry pi zero w 2
services:
  ghost:
    image: ghost:${GHOST_VERSION}
    restart: always
    ports:
      - "${PORT}:2368"
      - "80:2368"
      - "443:2368"
    depends_on:
      - db
    environment:
      url: ${URL}
      database__client: mysql
      database__connection__host: db
      database__connection__user: ${MARIADB_USER}
      database__connection__password: ${MARIADB_PASS}
      database__connection__database: ${MARIADB_DB}
      mail__transport: SMTP
      mail__options__host: ${MAIL_HOST}
      mail__options__port: 587
      mail__options__auth__user: ${MAIL_USER}
      mail__options__auth__pass: ${MAIL_PASS}
      mail__from: ghost <${MAIL_FROM}>
    volumes:
      - ./content:/var/lib/ghost/content
#      - ./config.json:/var/lib/ghost/config.production.json
  db:
    image: ${MARIADB_PREFIX}mariadb:${MARIADB_VERSION}
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
      MYSQL_USER: ${MARIADB_USER}
      MYSQL_PASSWORD: ${MARIADB_PASS}
      MYSQL_DATABASE: ${MARIADB_DB}
    volumes:
      - ./mariadb:/config
    ports:
      - 3306:3306
