version: '3'

services:
  # Database
  mariadb:
    image: mariadb:latest
    volumes:
      - 'mariadb_data:/var/lib/mysql'
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_USER: wordpress
      MARIADB_DATABASE: wordpress
      MARIADB_PASSWORD: wordpress
    networks:
      - wpsite
  # Wordpress
  wordpress:
    depends_on:
      - mariadb
    image: docker.io/bitnami/wordpress-nginx:latest
    ports:
      - '80:8080'
      - '443:8443'
    volumes:
      - './wordpress_data:/bitnami/wordpress'
#      - 'wordpress_data:/bitnami/wordpress'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      WORDPRESS_USERNAME: user
      WORDPRESS_PASSWORD: pass
      WORDPRESS_EMAIL: hi@hi.com
      WORDPRESS_FIRST_NAME: Hans
      WORDPRESS_LAST_NAME: W
      WORDPRESS_BLOG_NAME: skaleio wpsite
      WORDPRESS_DATABASE_HOST: mariadb
      WORDPRESS_DATABASE_PORT_NUMBER: 3306
      WORDPRESS_DATABASE_USER: wordpress
      WORDPRESS_DATABASE_NAME: wordpress
      WORDPRESS_DATABASE_PASSWORD: wordpress
    networks:
      - wpsite
networks:
  wpsite: null
volumes:
  mariadb_data: null
  wordpress_data:
    driver : local
